Repository crossplane-contrib/provider-aws, pull requests merged in 2021-11, with the labels that each got.

#734 Implement Amazon MQ service
  Makefile
  apis/aws.go
  apis/mq/v1alpha1/custom_types.go
  apis/mq/v1alpha1/generator-config.yaml
  apis/mq/v1alpha1/referencers.go
  apis/mq/v1alpha1/zz_broker.go
  apis/mq/v1alpha1/zz_doc.go
  apis/mq/v1alpha1/zz_enums.go
  apis/mq/v1alpha1/zz_generated.deepcopy.go
  apis/mq/v1alpha1/zz_generated.managed.go
  apis/mq/v1alpha1/zz_generated.managedlist.go
  apis/mq/v1alpha1/zz_groupversion_info.go
  apis/mq/v1alpha1/zz_types.go
  apis/mq/v1alpha1/zz_user.go
  examples/mq/activemq-broker.yaml
  examples/mq/activemq-user.yaml
  examples/mq/rabbitmq-broker.yaml
  package/crds/mq.aws.crossplane.io_brokers.yaml
  package/crds/mq.aws.crossplane.io_users.yaml
  pkg/clients/mq/mq.go
  pkg/clients/mq/mq_test.go
  pkg/controller/aws.go
  pkg/controller/mq/broker/setup.go
  pkg/controller/mq/broker/zz_controller.go
  pkg/controller/mq/broker/zz_conversions.go
  pkg/controller/mq/user/setup.go
  pkg/controller/mq/user/zz_controller.go
  pkg/controller/mq/user/zz_conversions.go
Labels: size/L

#924 Tweak DynamoDb table update logic and connection secret keys
  pkg/controller/dynamodb/table/hooks.go
Labels: backport release-0.20

#913 fix multi-region with injected identity - after v2 migration v0.20.0
  pkg/clients/aws.go
Labels: backport release-0.20

#779 Implements kms(cmk) alias
  apis/kms/v1alpha1/custom_types.go
  apis/kms/v1alpha1/generator-config.yaml
  apis/kms/v1alpha1/referencers.go
  apis/kms/v1alpha1/zz_alias.go
  apis/kms/v1alpha1/zz_generated.deepcopy.go
  apis/kms/v1alpha1/zz_generated.managed.go
  apis/kms/v1alpha1/zz_generated.managedlist.go
  apis/kms/v1alpha1/zz_types.go
  examples/kms/alias.yaml
  package/crds/kms.aws.crossplane.io_aliases.yaml
  pkg/controller/aws.go
  pkg/controller/kms/alias/setup.go
  pkg/controller/kms/alias/zz_controller.go
  pkg/controller/kms/alias/zz_conversions.go
Labels: size/M

#763 s3: resolve bucket ARN in replication config references
  apis/s3/v1beta1/referencers.go
  apis/s3/v1beta1/replicationConfiguration_types.go
  examples/iam/role.yaml
  examples/iam/rolepolicyattachment.yaml
  examples/s3/bucket.yaml
  package/crds/s3.aws.crossplane.io_buckets.yaml
Labels: size/S

#950 Key alias fix
  apis/kms/v1alpha1/alias.go
  apis/kms/v1alpha1/custom_types.go
  apis/kms/v1alpha1/generator-config.yaml
  apis/kms/v1alpha1/zz_generated.deepcopy.go
  apis/kms/v1alpha1/zz_generated.resolvers.go
  apis/kms/v1alpha1/zz_types.go
  examples/kms/alias.yaml
  package/crds/kms.aws.crossplane.io_aliases.yaml
  pkg/controller/kms/alias/controller.go
  pkg/controller/kms/alias/conversions.go
  pkg/controller/kms/alias/setup.go
  pkg/controller/kms/key/setup.go
Labels: backport release-0.21

#952 Manually late-init CloudFront Distributions
  pkg/clients/aws.go
  pkg/clients/aws_test.go
  pkg/controller/cloudfront/cachepolicy/lateinit.go
  pkg/controller/cloudfront/cachepolicy/lateinit_test.go
  pkg/controller/cloudfront/cachepolicy/setup.go
  pkg/controller/cloudfront/distribution/lateinit.go
  pkg/controller/cloudfront/distribution/lateinit_test.go
  pkg/controller/cloudfront/distribution/setup.go
Labels: backport release-0.21

#916 fix s3 nil paymentConfiguration preventing bucket from being ready
  pkg/controller/s3/bucket/requestPaymentConfig.go
  pkg/controller/s3/bucket/requestPaymentConfig_test.go
  pkg/controller/s3/bucket_test.go
Labels: backport release-0.21

#917 fix s3 notificationConfiguration
  pkg/controller/s3/bucket/notificationConfig.go
  pkg/controller/s3/bucket/notificationConfig_test.go
Labels: backport release-0.21

#963 S3 test nitpicks
  pkg/controller/s3/bucket/CORSConfig_test.go
  pkg/controller/s3/bucket/accelerateConfig_test.go
  pkg/controller/s3/bucket/lifecycleConfig_test.go
  pkg/controller/s3/bucket/loggingConfig_test.go
  pkg/controller/s3/bucket/notificationConfig_test.go
  pkg/controller/s3/bucket/replicationConfig_test.go
  pkg/controller/s3/bucket/requestPaymentConfig_test.go
  pkg/controller/s3/bucket/sseConfig_test.go
  pkg/controller/s3/bucket/taggingConfig_test.go
  pkg/controller/s3/bucket/versioningConfig_test.go
  pkg/controller/s3/bucket/websiteConfig_test.go
Labels: backport release-0.21

#911 support for s3 replicationConfiguration with delete marker enabled (and fixes)
  apis/s3/v1beta1/replicationConfiguration_types.go
  package/crds/s3.aws.crossplane.io_buckets.yaml
  pkg/controller/s3/bucket/replicationConfig.go
  pkg/controller/s3/bucket/replicationConfig_test.go
Labels: backport release-0.21

#973 Accomodate DynamoDB API's implied defaults
  examples/dynamodb/table.yaml
  pkg/clients/aws.go
  pkg/controller/dynamodb/table/hooks.go
  pkg/controller/dynamodb/table/hooks_test.go
Labels: backport release-0.21
